### PR TITLE
NOISSUE - Update twins.md link to service schema.

### PR DESCRIPTION
**Pull request by tritao**
### What does this do?

Update twins.md link to service schema

### CODE REVIEW

**Review by drasko — COMMENTED** [review]
LGTM

**Comment by drasko** [comment]
@tritao thanks for the PR.

Please sign your commits so that we can merge. Instructions are here: https://github.com/mainflux/docs/pull/56/checks?check_run_id=1295270814

**Review by dborovcanin — DISMISSED** [review]

**Review by drasko — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
@tritao please sign your commits and update the branch.

**Comment by tritao** [comment]
Done

**Comment by drasko** [comment]
Looks like there are still conflicts...

**Comment by manuio** [comment]
@tritao can you fix these conflicts and sign your commits please?

**Comment by tritao** [comment]
I've now rebased this twice and it still says there are conflicts, maybe because I originally did this change from the Github UI.
I have wasted an unreasonable amount of time trying to get such a trivial commit in at this point, so I will just close this.

A team member can do a manual edit of this via Github UI in less than a minute.

**Comment by drasko** [comment]
@tritao very sorry for this, I though that it was a DCO failing.

Thanks for this correction. Conflicts resolved and PR merged!

**Pull request merged**
