### PR TITLE
NOISSUE - Changed 'informations' to information 

### PR DESCRIPTION
**Pull request by apmurali**
Changed 'informations' to information

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Grammar fix
### Which issue(s) does this PR fix/relate to?
-
### List any changes that modify/break current functionality
No breaking changes
### Have you included tests for your changes?
None
### Did you document any new/modified functionality?
Not applicable

### CODE REVIEW

**Comment by manuio** [comment]
@apmurali Please, sign your commits. DCO is failling

**Comment by apmurali** [comment]
@manuio Commit signed. Thank you for your patience. 😅

**Review by manuio — APPROVED** [review]
LGTM

**Review by mteodor — APPROVED** [review]

**Comment by manuio** [comment]
Thanks @apmurali !

**Pull request merged**
