### PR TITLE
NOISSUE - Add current version of go and protoc

### PR DESCRIPTION
**Pull request by rodneyosodo**
Signed-off-by: Rodney Osodo <blackd0t@protonmail.com>

### What does this do?
Adds to the documentation the new updated versions of golang and protoc

### Which issue(s) does this PR fix/relate to?
It doesn't relate to previous issues

### List any changes that modify/break current functionality
No changes

### Have you included tests for your changes?
No tests

### Did you document any new/modified functionality?
Yes

### CODE REVIEW

**Comment by drasko** [comment]
@0x6f736f646f please rename your PR according to the Mainflux standards described in the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) - PR names start with `MF-[issue-number] - `, or `NOISSUE -` if PR introduces changes for which an appropriate issue has not been opened.

For example - your PR should be named `NOISSUE - Bump versions of go and protoc`

**Review by drasko — APPROVED** [review]
LGTM

**Review by blokovi — APPROVED** [review]

**Comment by rodneyosodo** [comment]
> @0x6f736f646f please rename your PR according to the Mainflux standards described in the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) - PR names start with `MF-[issue-number] - `, or `NOISSUE -` if PR introduces changes for which an appropriate issue has not been opened.
> 
> For example - your PR should be named `NOISSUE - Bump versions of go and protoc`

Done

**Comment by drasko** [comment]
Merged!

Thanks @0x6f736f646f

**Pull request merged**
