### PR TITLE
NOISSUE- Fix groups

### PR DESCRIPTION
**Pull request by WashingtonKK**
Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Fixes 404 on groups

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
Not necessary

### CODE REVIEW

**Review by SammyOina — APPROVED** [review]

**Review by rodneyosodo — APPROVED** [review]

**Comment by drasko** [comment]
Why are groups removed from the documentation, and where are they moved now?

Is this removing them just from the index? What about .md file that is the real description?

**Comment by WashingtonKK** [comment]
@rodneyosodo has more context on this.

**Comment by rodneyosodo** [comment]
> Why are groups removed from the documentation, and where are they moved now?
> 
> Is this removing them just from the index? What about .md file that is the real description?

Initially groups were at https://github.com/rodneyosodo/docs/blob/NOISSUE-format/docs/api.md#groups and https://github.com/rodneyosodo/docs/blob/NOISSUE-format/docs/cli.md#groups-management. With this PR https://github.com/mainflux/docs/pull/146, I updated in the respective places

**Comment by rodneyosodo** [comment]
> Is this removing them just from the index?

Yes, it is.

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
