### PR TITLE
MF-68 - Fix link to Auth service in provision page

### LINKED ISSUE #68: Fix documentation with new Auth service in provision page
**BUG REPORT**

After the merging of authz and authn service https://github.com/mainflux/mainflux/pull/1313, links to [Auth](https://github.com/mainflux/mainflux/tree/master/auth) doesn't work.

There is also some old information related to Authn in the kubernetes page.

### PR DESCRIPTION
**Pull request by jonathandreyer**
### What does this do?
Fix error to Auth service in provision page.

### Which issue(s) does this PR fix/relate to?
Resolves #68.

### Notes
It seems that there are also few words with Authn in the kubernetes page, but I didn't know if it is still relevant.

### CODE REVIEW

**Review by manuio — APPROVED** [review]

**Review by manuio — CHANGES_REQUESTED** [review]
DCO is failing, please sign your commit

**Comment by jonathandreyer** [comment]
Your are right, I have forgot it.

**Comment by jonathandreyer** [comment]
@manuio It is fixed.

**Review by manuio — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
