### PR TITLE
NOISSUE - Add missing client-id (thing_name) argument in Mosquitto commands for mTLS docs

### PR DESCRIPTION
**Pull request by dulataldazharov**
Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Adds missing `-i <thing_name>` argument in mosquitto commands for MQTTS under the following mTLS documentation: https://docs.mainflux.io/authentication/#mutual-tls-authentication-with-x509-certificates

### Which issue(s) does this PR fix/relate to?
No issue created, since the change is quite small.

### List any changes that modify/break current functionality
Just a minor docs fix. No breaking change.

### Have you included tests for your changes?
This is documentation change, no need.

### Did you document any new/modified functionality?
Not applicable.

### CODE REVIEW

**Review by drasko — COMMENTED** [review]
No need for `thing_name` AFIK.

@rodneyosodo @dborovcanin @fbugarski please confirm.

**Comment by dulataldazharov** [comment]
> No need for `thing_name` AFIK.
> 
> @rodneyosodo @dborovcanin @fbugarski please confirm.

In my personal experience, without mTLS it works fine without the thing_name argument. However, with mTLS mode, it didn’t work, and the logs in mainflux showed client_id doesn’t exist error. When I simply added the argument it worked for me.
I used mosquitto client installed from brew.
My OS is Ubuntu 22.04, if that might be helpful.

**Comment by rodneyosodo** [comment]
@drasko Yes, `client id` is needed and a suitable `client id` would be `thing name`

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Update also here

https://github.com/mainflux/docs/blob/fd2415cd2e5561b961c094dc54b0ac06d2b990c5/docs/messaging.md?plain=1#L20

**Comment by drasko** [comment]
@rodneyosodo please clarify, is the name mandatory, or ID os sufficient?

**Comment by rodneyosodo** [comment]
The `thing_name` which is `client_id` is mandatory. Without it you get
```
mainflux-mqtt   | {"level":"info","message":"Accepted new client","ts":"2023-01-16T07:16:12.770083617Z"}
mainflux-mqtt   | {"level":"error","message":"disconnected client_id  and username 1cac465e-2e40-4246-ac25-e350cce6f806","ts":"2023-01-16T07:16:12.771591378Z"}
mainflux-mqtt   | {"level":"warn","message":"Broken connection for client:  with error: failed proxying from MQTT broker to MQTT clientclient_id not found","ts":"2023-01-16T07:16:12.772104883Z"}
```

**Comment by dulataldazharov** [comment]
> Update also here
> 
> https://github.com/mainflux/docs/blob/fd2415cd2e5561b961c094dc54b0ac06d2b990c5/docs/messaging.md?plain=1#L20

When mTLS mode is turned off, i.e. mainflux is running without AUTH=x509, it works fine without the client_id. It’s only when mTLS is turned on, it requires client_id. Should we still add client-id here (mTLS is not used here)?

**Comment by dborovcanin** [comment]
Client ID is required for each MQTT message, and [Mosquitto will generate one](https://mosquitto.org/man/mosquitto_sub-1.html) if not set by the user. The client ID can be anything, and enforcing the user to use a thing name can be confusing. What concerns me is this `However, with mTLS mode, it didn’t work, and the logs in mainflux showed client_id doesn’t exist error. When I simply added the argument it worked for me`. @rodneyosodo Can you, please, double-check and test this scenario?

**Comment by rodneyosodo** [comment]
I'd suggest using `--id-prefix mainflux` rather than having `-i <thing_name>`

**Comment by rodneyosodo** [comment]
I'd suggest using `--id-prefix mainflux` rather than having `-i <thing_name>`

**Comment by dborovcanin** [comment]
Any update on this? @rodneyosodo Did you test the mTLS scenario? Also, from the Mosquitto [docs](https://mosquitto.org/man/mosquitto_pub-1.html), looks like `--id-prefix` flag is not too helpful because ID is still auto-generated, and for reproducible behavior, we'll need to specify an ID, rather than generate it. In the examples - we don't need to enforce any particular ID format, and the Thing name can only make it more confusing.

**Comment by manuio** [comment]
@dborovcanin This issue is very probably related to a recent addition when improving mqtt-adapter tests: https://github.com/mainflux/mainflux/blob/master/mqtt/handler.go#L80 
We can probably remove this client ID check to avoid having to set it.

**Comment by dborovcanin** [comment]
It is possible, but since [#1743](https://github.com/mainflux/mainflux/issues/1743) is using 0.13, it was probably there even before. But it's not a problem, we need ID anyways.

**Review by SammyOina — APPROVED** [review]

**Comment by dborovcanin** [comment]
@dulataldazharov  Client ID is related to MQTT protocol and not specific to Mainflux. It should not affect TLS or mTLS. That being said, it's fine to have ID set in the docs, it's just that ID does not have to be `<thing_name>`, but an arbitrary string.

**Comment by dborovcanin** [comment]
Closing this one due to inactivity. Our docs are up to date and `client-id` is not necessary for mosquitto tool to work with Mainflux.

**Pull request closed without merging**
